import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe5e5",
    paddingTop: 10,
    paddingHorizontal: 10,
    paddingBottom: 0,
    height: "auto",
  },
  scrollView: {
    flex: 1,
  },
  innerContainer: {
    paddingHorizontal: 10,
    height: "auto",
  },
  diaperInnerContainer: {
    backgroundColor: "#fff",
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 10,
    height: "auto",
    borderRadius: 20,
  },
  diaperContainer: {
    flex: 1,
  },
  diaperItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
  },
  diaperItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(137, 196, 255, 1.0)",
  },
  recordDiaperTitle: {
    color: "#45444",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 10,
  },
  recordPeeOrPoo: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  peeSection: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#E69ED8",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
    borderRadius: 10,
    width: "40%",
    paddingVertical: 5,
    paddingHorizontal: 3,
  },
  pooSection: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#8DD2F2",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
    borderRadius: 10,
    width: "40%",
    paddingVertical: 5,
    paddingHorizontal: 3,
  },
  selectedSection: {
    borderWidth: 5,
    borderColor: "#b3afaf",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#FFF",
    marginLeft: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxInner: {
    width: 12,
    height: 12,
    backgroundColor: "#FFF",
    borderRadius: 2,
  },
  peeIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pooIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  peeIconText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  pooIconText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  timePickerContainer: {
    backgroundColor: "#f5f5f5",
    borderRadius: 5,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  timePicker: {
    height: 80,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginTop: 50,
    marginBottom: 10,
  },
  button: {
    width: 130,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#9e9e9e',
  },
  okButton: {
    backgroundColor: '#ff69b4',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  memoSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
    marginVertical: 20,
  },
  memoIcon: {
    width: 35,
    height: 35,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "gray",
    marginRight: 5,
  },
  memoLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#45444",
  },
  memoInput: {
    borderWidth: 2,
    borderColor: "#45444433",
    borderRadius: 8,
    padding: 12,
    height: 100,
    textAlignVertical: "top",
    fontSize: 14,
    color: "#333333",
  },
});

export default styles; 