import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe5e5",
    paddingTop: 10,
    paddingHorizontal: 10,
    paddingBottom: 0,
    height: "auto",
  },
  scrollView: {
    flex: 1,
  },
  innerContainer: {
    paddingHorizontal: 10,
    height: "auto",
  },
  recordSectionContainer: {
    backgroundColor: "#fff",
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 10,
    height: "auto",
    borderRadius: 20,
  },
  recordSectionTitle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
  },
  recordSectionTitleText: {
    color: "#45444",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 10,
  },
  mealIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(137, 196, 255, 1.0)",
  },
  recordMotherOrMilk: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  motherSection: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#E69ED8",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
    borderRadius: 10,
    width: "40%",
    paddingVertical: 5,
    paddingHorizontal: 3,
  },
  selectedSection: {
    borderWidth: 5,
    borderColor: "#b3afaf",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#FFF",
    marginLeft: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxInner: {
    width: 12,
    height: 12,
    backgroundColor: "#FFF",
    borderRadius: 2,
  },
  motherIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  motherIconText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  milkSection: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#8DD2F2",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
    gap: 5,
    borderRadius: 10,
    width: "40%",
    paddingVertical: 5,
    paddingHorizontal: 3,
  },
  milkIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  milkIconText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  timePickerSection: {
    marginVertical: 20,
  },
  clockIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#b8e68a",
  },
  timePickerLabel: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 5,
    marginLeft: 10,
  },
  timePickerContainer: {
    backgroundColor: "#f5f5f5",
    borderRadius: 5,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  timePicker: {
    height: 80,
  },
  LRSection: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 180,
  },
  leftLabel: {
    fontSize: 20,
    fontWeight: "bold",
  },
  rightLabel: {
    fontSize: 20,
    fontWeight: "bold",
  },
  durationPickerContainerWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    width: "100%",
  },
  durationPickerContainer: {
    backgroundColor: "#ffffff",
    marginVertical: 5,
    flex: 1,
    marginHorizontal: 10,
  },
  durationPicker: {
    height: 30,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginTop: 50,
    marginBottom: 10,
  },
  button: {
    width: 130,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#ff6b6b',
  },
  okButton: {
    backgroundColor: '#ff69b4',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  milkAmountPickerSection: {
    marginVertical: 30,
  },
  milkCanIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8DD2F2",
  },
  milkAmountPickerContainer: {
    backgroundColor: "#ffffff",
    marginVertical: 5,
    flex: 1,
    marginHorizontal: 10,
  },
  milkAmountPicker: {
    height: 30,
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    borderColor: '#f44336',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  errorText: {
    color: '#d32f2f',
    fontSize: 14,
    textAlign: 'center',
  },
});
export default styles;

