import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe5e5",
    paddingTop: 10,
    paddingHorizontal: 10,
    paddingBottom: 0,
  },
  scrollView: {
    flex: 1,
  },
  innerContainer: {
    paddingHorizontal: 10,
  },
  infoBox: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 20,
    marginBottom: 20,
  },
  infoText: {
    fontSize: 14,
    marginBottom: 5,
    color: "#333",
  },
  recordSectionContainer: {
    backgroundColor: "#fff",
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 10,
    height: "auto",
    borderRadius: 20,
  },
  recordSectionTitle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
  },
  recordSectionTitleText: {
    color: "#454444",
    fontSize: 14,
    fontWeight: "bold",
  },
  recordSection: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 5,
  },
  recordColumn: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "auto",
    width: "60%",
  },
  recordRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    height: "auto",
    width: "100%",
    gap: 5,
  },
  recordButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: 10,
    width: "60%",
    paddingVertical: 5,
    paddingHorizontal: 3,
    gap: 5,
  },
  recordButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  recordMeasurements: {
    display: "flex",
    width: "auto",
    height: "auto",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: "#73ace6",
    borderRadius: 20,
    padding: 10,
    marginRight: 5,
  },
  recordMeasurement: {
    display: "flex",
    flexDirection: "row",
    width: "auto",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
  },
  timeLineSectionContainer: {
    backgroundColor: "#fff",
    marginBottom: 10,
    paddingVertical: 5,
    height: "auto",
    borderRadius: 20,
  },
  timeLineSection: {
  },
  timeLineSectionTitle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginHorizontal: 10,
    marginBottom: 5,
    gap: 5,
  },
  timeLineItems: {
    flexDirection: "column",
  },
  timeLineItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  timeLineItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  timeLineText: {
    color: "#454444",
    fontSize: 14,
    fontWeight: "bold",
    width: "30%",
  },
  timestamp: {
    color: "#454444",
    fontSize: 14,
    fontWeight: "bold",
    width: "30%",
  },
  logText:{
    color: "rgba(69, 68, 68, 0.5)",
    fontSize: 10,
    width: "30%",
  }
});

export default styles;
