import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe5e5",
    paddingTop: 10,
    paddingHorizontal: 10,
    paddingBottom: 0,
  },
  scrollView: {
    flex: 1,
  },
  innerContainer: {
    paddingHorizontal: 10,
  },
  header: {
    backgroundColor: "#ffadad",
    padding: 10,
    borderRadius: 20,
    marginBottom: 20,
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileName: {
    fontSize: 22,
    fontWeight: "bold",
    marginLeft: 10,
    color: "#333",
  },
  profileAge: {
    fontSize: 16,
    color: "#555",
  },
  participants: {
    flexDirection: "row",
    marginTop: 10,
  },
  iconButton: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  participantText: {
    fontSize: 16,
    marginLeft: 5,
  },
  infoBox: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 20,
    marginBottom: 20,
  },
  infoText: {
    fontSize: 14,
    marginBottom: 5,
    color: "#333",
  },
  recordSection: {
    backgroundColor: "#fff",
    height: "auto",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderRadius: 20,
    gap: 5,
    marginBottom: 20,
  },
  recordColumn: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "auto",
    width: "60%",
  },
  recordRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    height: "auto",
    width: "100%",
    gap: 5,
  },
  recordButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: 10,
    width: "60%",
    paddingVertical: 5,
    paddingHorizontal: 3,
    gap: 5,
  },
  recordButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  recordMeasurements: {
    display: "flex",
    width: "auto",
    height: "auto",
    flexDirection: "column",
    justifyContent: "space-between",
    backgroundColor: "#73ace6",
    borderRadius: 20,
    padding: 10,
    marginRight: 5,
  },
  recordMeasurement: {
    display: "flex",
    flexDirection: "row",
    width: "auto",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
  },
  timeLineSection: {
    backgroundColor: "#fff",
    height: "auto",
    borderRadius: 20,
    marginBottom: 20,
  },
  timeLineItems: {
    flexDirection: "column",
  },
  timeLineItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  timeLineItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  timeLineText: {
    color: "#454444",
    fontSize: 14,
    fontWeight: "bold",
    width: "45%",
  },
  timestamp: {
    color: "#454444",
    fontSize: 14,
    fontWeight: "bold",
    width: "20%",
  },
  logText:{
    color: "rgba(69, 68, 68, 0.5)",
    fontSize: 10,
    width: "25%",
  },
  navigation: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    marginHorizontal: 10,
  },
  bottomNavwrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
  },
  bottomNav: {
    width: 45,
    height: 45,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  navButton: {
    backgroundColor: "#eee",
    padding: 10,
    borderRadius: 10,
  },
});

export default styles;
